version: "3.8"

volumes:
  mysql57:
    name: mysql57

services:
  mysql:
    image: mysql:5.7.21
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estimate-tool
    volumes:
      - mysql57:/var/lib/mysql

  web:
    build: docker/nginx
    ports:
      - 8081:80
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_ALIAS_DOMAIN: localhost
